spring.application.name=tpms

#groq
groq.api.key=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.show-sql=true
spring.h2.console.settings.web-allow-others=true
spring.datasource.type=com.zaxxer.hikari.HikariDataSource



springdoc.swagger-ui.path=/swagger-ui
springdoc.api-docs.path=/api-docs